source "https://rubygems.org"
ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1" 
gem "puma", ">= 5.0"


gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11.0"
gem "rack-cors"
gem "jsonapi-serializer"
gem "sidekiq", "~> 7.0"
gem "kaminari", "~> 1.2"
gem "dotenv-rails", groups: [:development, :test]
gem "bcrypt", "~> 3.1.7"


gem "sprockets-rails"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 3.2"
end

group :development do
  gem "web-console"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record", "~> 2.1"
end